---
- name: Copy artifact.tar.gz to EC2
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Start the app
  shell: |
    cd /home/ubuntu/
    tar -xvf artifact.tar.gz
    npm install pm2 -g
    npm install
    pm2 stop default
    pm2 start npm -- start